# Generated by Django 4.1.11 on 2023-09-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="pid",
            field=models.CharField(default="null", max_length=200),
            preserve_default=False,
        ),
    ]
