# Generated by Django 4.1.11 on 2023-09-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0002_post_pid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="id",
        ),
        migrations.AlterField(
            model_name="post",
            name="pid",
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
